In [17]:
import numpy as np
list_ = ['1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Python List:

Lists are the inbuilt data structure of python.
We can store elements of different types in the list.
Items in the list are enclosed between square brackets and separated by commas.
We can even nest lists with other data structures like lists, dictionaries, tuples, etc.


Python Array:

Arrays are not the in-built data structure readily available in Python.
We must import the array from the 'array' or 'numpy' module.
Array stores elements of similar types. If we try to store elements of different types, it will throw an error.
We can only store elements of the same types in the array.

In [18]:
print(type(list_))

<class 'list'>


In [19]:
print(type(array_list))

<class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [20]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [21]:
array_list.dtype

dtype('<U1')

Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [22]:
array_list = np.array(object = list_, dtype = int)

In [23]:
array_list

array([1, 2, 3, 4, 5])

In [24]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [25]:
array_list.dtype

dtype('int64')

In [26]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [27]:
num_array.shape

(2, 3)

In [28]:
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [33]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [34]:
import numpy.matlib as nm
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])